files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
  - source: /app/src/main/res/values/userpreferences.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
  - source: /app/src/main/res/values/compose.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%

commit_message: [ci skip]